{% set xorg_name = "util-macros" %}
{% set xorg_category = "util" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.20.1" %}
{% set sha256 = "0b308f62dce78ac0f4d9de6888234bf170f276b64ac7c96e99779bb4319bcef5" %}
{% set am_version = "1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - pkg-config
    - m2-base  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - make     # [unix]
    - m2-make  # [win]
  host:

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Development utility macros for X.org software.

extra:
  recipe-maintainers:
    - pkgw
