{% set xorg_name = "util-macros" %}
{% set xorg_category = "util" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.19.3" %}
{% set sha256 = "0f812e6e9d2786ba8f54b960ee563c0663ddbe2434bf24ff193f5feab1f31971" %}
{% set am_version = "1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - pkg-config
    - m2-base  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - make  # [unix]
  host:

test:
  commands:

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Development utility macros for X.org software.

extra:
  recipe-maintainers:
    - pkgw
